[build]
  # This is the directory to change to before starting a build
  base = "."
  
  # This is the directory that you are publishing from (relative to root of your repo)
  publish = "dist/public"
  
  # This will be your build command
  command = "npm run build"
  
  # Functions directory
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"
  SENDGRID_API_KEY = "${SENDGRID_API_KEY}"